=== MoodyAir/epam-task2/src/main/resources/schema/gem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://epam.zlatamigas.xmltask/gems"
        xmlns:tns="http://epam.zlatamigas.xmltask/gems"
        elementFormDefault="qualified">

    <complexType name="gem">
        <sequence>
            <element name="origin" type="tns:origin"/>
            <element name="extraction-time" type="gYearMonth"/>
            <element name="color" type="string"/>
            <element name="transparency" type="tns:transparency"/>
            <element name="faces" type="positiveInteger"/>
            <element name="mass" type="tns:mass"/>
        </sequence>
        <attribute name="id" type="tns:id" use="required"/>
        <attribute name="name" type="string" default="Gem stone"/>
    </complexType>

    <complexType name="precious">
        <complexContent>
            <extension base="tns:gem">
                <sequence>
                    <element name="type" type="tns:precious-type"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="semi-precious">
        <complexContent>
            <extension base="tns:gem">
                <sequence>
                    <element name="implementation" type="string" minOccurs="0" maxOccurs="1" default="unknown"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <simpleType name="origin">
        <restriction base="string">
            <enumeration value="South America"/>
            <enumeration value="North America"/>
            <enumeration value="Europe"/>
            <enumeration value="Asia"/>
            <enumeration value="Australia"/>
            <enumeration value="Oceania"/>
        </restriction>
    </simpleType>
    <simpleType name="id">
        <restriction base="ID">
            <pattern value="\w-\d{6}"/>
        </restriction>
    </simpleType>
    <simpleType name="transparency">
        <restriction base="integer">
            <minInclusive value="0"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>
    <simpleType name="mass">
        <restriction base="double">
            <minExclusive value="0"/>
        </restriction>
    </simpleType>

    <simpleType name="precious-type">
        <restriction base="string">
            <enumeration value="diamond"/>
            <enumeration value="sapphire"/>
            <enumeration value="ruby"/>
            <enumeration value="emerald"/>
        </restriction>
    </simpleType>


    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:gem" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="gem" type="tns:gem" abstract="true"/>
    <element name="precious" type="tns:precious" substitutionGroup="tns:gem"/>
    <element name="semi-precious" type="tns:semi-precious" substitutionGroup="tns:gem"/>

</schema>

=== MoodyAir/epam-task2/src/test/resources/data/gem_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://epam.zlatamigas.xmltask/gems"
      xsi:schemaLocation="http://epam.zlatamigas.xmltask/gems ../schema/gem.xsd">

    <precious id="A-000001">
        <origin>South America</origin>
        <extraction-time>2002-01</extraction-time>
        <color>red</color>
        <transparency>12</transparency>
        <faces>2</faces>
        <mass>3</mass>
        <type>ruby</type>
    </precious>
    <precious name="Esmeralda" id="A-000002">
        <origin>North America</origin>
        <extraction-time>2022-02</extraction-time>
        <color>green</color>
        <transparency>90</transparency>
        <faces>8</faces>
        <mass>12.2</mass>
        <type>emerald</type>
    </precious>
    <semi-precious id="B-000001" name="Quartz">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>23</mass>
    </semi-precious>
    <semi-precious id="B-000002" name="Quartz">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>24</mass>
    </semi-precious>
    <semi-precious id="B-000003" name="Quartz">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>19</mass>
    </semi-precious>
    <semi-precious id="B-000004" name="Quartz">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>19</mass>
    </semi-precious>
    <precious id="A-000003">
        <origin>South America</origin>
        <extraction-time>2002-01</extraction-time>
        <color>red</color>
        <transparency>12</transparency>
        <faces>2</faces>
        <mass>3</mass>
        <type>ruby</type>
    </precious>
    <precious id="A-000004">
        <origin>South America</origin>
        <extraction-time>2002-01</extraction-time>
        <color>red</color>
        <transparency>12</transparency>
        <faces>2</faces>
        <mass>3</mass>
        <type>ruby</type>
    </precious>
    <precious id="A-000005">
        <origin>South America</origin>
        <extraction-time>2002-01</extraction-time>
        <color>red</color>
        <transparency>12</transparency>
        <faces>2</faces>
        <mass>3</mass>
        <type>ruby</type>
    </precious>
    <precious id="A-000006">
        <origin>North America</origin>
        <extraction-time>2002-01</extraction-time>
        <color>white</color>
        <transparency>90</transparency>
        <faces>9</faces>
        <mass>3</mass>
        <type>diamond</type>
    </precious>
    <semi-precious id="B-000005" name="Quartz">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>23</mass>
    </semi-precious>
    <semi-precious id="B-000006" name="Quartz">
        <origin>Oceania</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>24.9</mass>
    </semi-precious>
    <semi-precious name="Quartz" id="B-000007">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>19</mass>
    </semi-precious>
    <semi-precious id="B-000008">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>19</mass>
    </semi-precious>
    <precious id="A-000007">
        <origin>South America</origin>
        <extraction-time>2002-01</extraction-time>
        <color>red</color>
        <transparency>12</transparency>
        <faces>2</faces>
        <mass>3</mass>
        <type>ruby</type>
    </precious>
    <precious id="A-000008">
        <origin>Europe</origin>
        <extraction-time>2012-12</extraction-time>
        <color>black</color>
        <transparency>90</transparency>
        <faces>9</faces>
        <mass>3</mass>
        <type>sapphire</type>
    </precious>
</gems>

=== MoodyAir/epam-task2/src/test/resources/data/gem_2.xml
<?xml version="1.0" encoding="utf-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://test.zlatamigas.xmltask/gems"
      xsi:schemaLocation="http://test.zlatamigas.xmltask/gems ../schema/gem.xsd">

    <precious name="Esmeralda" id="A-000002">
        <origin>North America</origin>
        <extraction-time>2022-02</extraction-time>
        <color>green</color>
        <transparency>90</transparency>
        <faces>8</faces>
        <mass>12.2</mass>
        <type>emerald</type>
    </precious>
    <semi-precious id="B-000001" name="Quartz">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>23</mass>
    </semi-precious>
    <semi-precious id="B-000003">
        <origin>Asia</origin>
        <extraction-time>2017-03</extraction-time>
        <color>rose</color>
        <transparency>45</transparency>
        <faces>19</faces>
        <mass>19</mass>
        <implementation>jewelry</implementation>
    </semi-precious>

</gems>
